### PR TITLE
Fix build with Qt 5.14

### PR DESCRIPTION
**Pull request by rezso**
In file included from Renderer.h:10,
                 from PropDialog.h:9,
                 from PropDialog.cpp:8:
Annotation.h:38:11: error: ‘QImage’ does not name a type

### CODE REVIEW

**Comment by q5sys** [comment]
LGTM.  Thanks for sending that in! If you find any other needed includes for 5.14, let us know.

**Comment by q5sys** [comment]
I'm going to let Ken merge this in, it's his project so I'll let him have the pleasure of merging.

**Review by beanpole135 — APPROVED** [review]
